void Calorimeter_elaser_ShowerEnergyDeposition()
{
//=========Macro generated from canvas: c1/c1
//=========  (Wed Jan 13 23:10:11 2021) by ROOT version 6.22/02
   TCanvas *c1 = new TCanvas("c1", "c1",10,32,700,500);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->Range(-0.05063291,-81.01265,0.2658228,425.3165);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.16);
   c1->SetRightMargin(0.05);
   c1->SetTopMargin(0.05);
   c1->SetBottomMargin(0.16);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderMode(0);
   
   TH1D *Shower_E__1 = new TH1D("Shower_E__1","Shower_E",300,0,0.75);
   Shower_E__1->SetBinContent(75,2);
   Shower_E__1->SetBinContent(76,2);
   Shower_E__1->SetBinContent(77,9);
   Shower_E__1->SetBinContent(78,11);
   Shower_E__1->SetBinContent(79,16);
   Shower_E__1->SetBinContent(80,24);
   Shower_E__1->SetBinContent(81,37);
   Shower_E__1->SetBinContent(82,53);
   Shower_E__1->SetBinContent(83,63);
   Shower_E__1->SetBinContent(84,68);
   Shower_E__1->SetBinContent(85,70);
   Shower_E__1->SetBinContent(86,85);
   Shower_E__1->SetBinContent(87,92);
   Shower_E__1->SetBinContent(88,93);
   Shower_E__1->SetBinContent(89,89);
   Shower_E__1->SetBinContent(90,66);
   Shower_E__1->SetBinContent(91,64);
   Shower_E__1->SetBinContent(92,53);
   Shower_E__1->SetBinContent(93,26);
   Shower_E__1->SetBinContent(94,22);
   Shower_E__1->SetBinContent(95,18);
   Shower_E__1->SetBinContent(96,16);
   Shower_E__1->SetBinContent(97,11);
   Shower_E__1->SetBinContent(98,4);
   Shower_E__1->SetBinContent(100,4);
   Shower_E__1->SetBinContent(101,1);
   Shower_E__1->SetMinimum(0);
   Shower_E__1->SetMaximum(400);
   Shower_E__1->SetEntries(999);
   Shower_E__1->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   Shower_E__1->SetLineColor(ci);
   Shower_E__1->SetLineStyle(2);
   Shower_E__1->SetLineWidth(2);
   Shower_E__1->SetMarkerStyle(20);
   Shower_E__1->SetMarkerSize(1.2);
   Shower_E__1->GetXaxis()->SetTitle("Shower Energy Deposition (GeV)");
   Shower_E__1->GetXaxis()->SetRange(1,100);
   Shower_E__1->GetXaxis()->SetLabelFont(42);
   Shower_E__1->GetXaxis()->SetLabelSize(0.05);
   Shower_E__1->GetXaxis()->SetTitleSize(0.05);
   Shower_E__1->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__1->GetXaxis()->SetTitleFont(42);
   Shower_E__1->GetYaxis()->SetTitle("Arbirtary Units");
   Shower_E__1->GetYaxis()->SetLabelFont(42);
   Shower_E__1->GetYaxis()->SetLabelSize(0.05);
   Shower_E__1->GetYaxis()->SetTitleSize(0.05);
   Shower_E__1->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__1->GetYaxis()->SetTitleFont(42);
   Shower_E__1->GetZaxis()->SetLabelFont(42);
   Shower_E__1->GetZaxis()->SetLabelSize(0.05);
   Shower_E__1->GetZaxis()->SetTitleSize(0.05);
   Shower_E__1->GetZaxis()->SetTitleOffset(1);
   Shower_E__1->GetZaxis()->SetTitleFont(42);
   Shower_E__1->Draw("");
   
   TH1D *Shower_E__2 = new TH1D("Shower_E__2","Shower_E",300,0,0.75);
   Shower_E__2->SetBinContent(55,4);
   Shower_E__2->SetBinContent(56,8);
   Shower_E__2->SetBinContent(57,12);
   Shower_E__2->SetBinContent(58,26);
   Shower_E__2->SetBinContent(59,36);
   Shower_E__2->SetBinContent(60,64);
   Shower_E__2->SetBinContent(61,75);
   Shower_E__2->SetBinContent(62,94);
   Shower_E__2->SetBinContent(63,102);
   Shower_E__2->SetBinContent(64,126);
   Shower_E__2->SetBinContent(65,114);
   Shower_E__2->SetBinContent(66,91);
   Shower_E__2->SetBinContent(67,68);
   Shower_E__2->SetBinContent(68,76);
   Shower_E__2->SetBinContent(69,36);
   Shower_E__2->SetBinContent(70,32);
   Shower_E__2->SetBinContent(71,17);
   Shower_E__2->SetBinContent(72,9);
   Shower_E__2->SetBinContent(73,4);
   Shower_E__2->SetBinContent(74,4);
   Shower_E__2->SetBinContent(76,1);
   Shower_E__2->SetEntries(999);
   Shower_E__2->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   Shower_E__2->SetLineColor(ci);
   Shower_E__2->SetLineWidth(2);
   Shower_E__2->SetMarkerStyle(20);
   Shower_E__2->SetMarkerSize(1.2);
   Shower_E__2->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__2->GetXaxis()->SetLabelFont(42);
   Shower_E__2->GetXaxis()->SetLabelSize(0.05);
   Shower_E__2->GetXaxis()->SetTitleSize(0.05);
   Shower_E__2->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__2->GetXaxis()->SetTitleFont(42);
   Shower_E__2->GetYaxis()->SetTitle("N positron");
   Shower_E__2->GetYaxis()->SetLabelFont(42);
   Shower_E__2->GetYaxis()->SetLabelSize(0.05);
   Shower_E__2->GetYaxis()->SetTitleSize(0.05);
   Shower_E__2->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__2->GetYaxis()->SetTitleFont(42);
   Shower_E__2->GetZaxis()->SetLabelFont(42);
   Shower_E__2->GetZaxis()->SetLabelSize(0.05);
   Shower_E__2->GetZaxis()->SetTitleSize(0.05);
   Shower_E__2->GetZaxis()->SetTitleOffset(1);
   Shower_E__2->GetZaxis()->SetTitleFont(42);
   Shower_E__2->Draw("same");
   
   TH1D *Shower_E__3 = new TH1D("Shower_E__3","Shower_E",300,0,0.75);
   Shower_E__3->SetBinContent(58,1);
   Shower_E__3->SetBinContent(59,3);
   Shower_E__3->SetBinContent(60,4);
   Shower_E__3->SetBinContent(61,5);
   Shower_E__3->SetBinContent(62,8);
   Shower_E__3->SetBinContent(63,31);
   Shower_E__3->SetBinContent(64,43);
   Shower_E__3->SetBinContent(65,52);
   Shower_E__3->SetBinContent(66,66);
   Shower_E__3->SetBinContent(67,82);
   Shower_E__3->SetBinContent(68,81);
   Shower_E__3->SetBinContent(69,115);
   Shower_E__3->SetBinContent(70,102);
   Shower_E__3->SetBinContent(71,95);
   Shower_E__3->SetBinContent(72,88);
   Shower_E__3->SetBinContent(73,70);
   Shower_E__3->SetBinContent(74,59);
   Shower_E__3->SetBinContent(75,33);
   Shower_E__3->SetBinContent(76,22);
   Shower_E__3->SetBinContent(77,18);
   Shower_E__3->SetBinContent(78,11);
   Shower_E__3->SetBinContent(79,6);
   Shower_E__3->SetBinContent(80,2);
   Shower_E__3->SetBinContent(81,1);
   Shower_E__3->SetBinContent(82,1);
   Shower_E__3->SetEntries(999);
   Shower_E__3->SetStats(0);

   ci = TColor::GetColor("#ff00ff");
   Shower_E__3->SetLineColor(ci);
   Shower_E__3->SetLineStyle(2);
   Shower_E__3->SetLineWidth(2);
   Shower_E__3->SetMarkerStyle(20);
   Shower_E__3->SetMarkerSize(1.2);
   Shower_E__3->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__3->GetXaxis()->SetLabelFont(42);
   Shower_E__3->GetXaxis()->SetLabelSize(0.05);
   Shower_E__3->GetXaxis()->SetTitleSize(0.05);
   Shower_E__3->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__3->GetXaxis()->SetTitleFont(42);
   Shower_E__3->GetYaxis()->SetTitle("N positron");
   Shower_E__3->GetYaxis()->SetLabelFont(42);
   Shower_E__3->GetYaxis()->SetLabelSize(0.05);
   Shower_E__3->GetYaxis()->SetTitleSize(0.05);
   Shower_E__3->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__3->GetYaxis()->SetTitleFont(42);
   Shower_E__3->GetZaxis()->SetLabelFont(42);
   Shower_E__3->GetZaxis()->SetLabelSize(0.05);
   Shower_E__3->GetZaxis()->SetTitleSize(0.05);
   Shower_E__3->GetZaxis()->SetTitleOffset(1);
   Shower_E__3->GetZaxis()->SetTitleFont(42);
   Shower_E__3->Draw("same");
   
   TH1D *Shower_E__4 = new TH1D("Shower_E__4","Shower_E",300,0,0.75);
   Shower_E__4->SetBinContent(46,2);
   Shower_E__4->SetBinContent(47,1);
   Shower_E__4->SetBinContent(48,3);
   Shower_E__4->SetBinContent(49,5);
   Shower_E__4->SetBinContent(50,20);
   Shower_E__4->SetBinContent(51,28);
   Shower_E__4->SetBinContent(52,48);
   Shower_E__4->SetBinContent(53,60);
   Shower_E__4->SetBinContent(54,96);
   Shower_E__4->SetBinContent(55,113);
   Shower_E__4->SetBinContent(56,127);
   Shower_E__4->SetBinContent(57,135);
   Shower_E__4->SetBinContent(58,116);
   Shower_E__4->SetBinContent(59,86);
   Shower_E__4->SetBinContent(60,67);
   Shower_E__4->SetBinContent(61,36);
   Shower_E__4->SetBinContent(62,23);
   Shower_E__4->SetBinContent(63,20);
   Shower_E__4->SetBinContent(64,8);
   Shower_E__4->SetBinContent(65,4);
   Shower_E__4->SetBinContent(66,1);
   Shower_E__4->SetEntries(999);
   Shower_E__4->SetStats(0);

   ci = TColor::GetColor("#ff00ff");
   Shower_E__4->SetLineColor(ci);
   Shower_E__4->SetLineWidth(2);
   Shower_E__4->SetMarkerStyle(20);
   Shower_E__4->SetMarkerSize(1.2);
   Shower_E__4->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__4->GetXaxis()->SetLabelFont(42);
   Shower_E__4->GetXaxis()->SetLabelSize(0.05);
   Shower_E__4->GetXaxis()->SetTitleSize(0.05);
   Shower_E__4->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__4->GetXaxis()->SetTitleFont(42);
   Shower_E__4->GetYaxis()->SetTitle("N positron");
   Shower_E__4->GetYaxis()->SetLabelFont(42);
   Shower_E__4->GetYaxis()->SetLabelSize(0.05);
   Shower_E__4->GetYaxis()->SetTitleSize(0.05);
   Shower_E__4->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__4->GetYaxis()->SetTitleFont(42);
   Shower_E__4->GetZaxis()->SetLabelFont(42);
   Shower_E__4->GetZaxis()->SetLabelSize(0.05);
   Shower_E__4->GetZaxis()->SetTitleSize(0.05);
   Shower_E__4->GetZaxis()->SetTitleOffset(1);
   Shower_E__4->GetZaxis()->SetTitleFont(42);
   Shower_E__4->Draw("same");
   
   TH1D *Shower_E__5 = new TH1D("Shower_E__5","Shower_E",300,0,0.75);
   Shower_E__5->SetBinContent(43,1);
   Shower_E__5->SetBinContent(44,1);
   Shower_E__5->SetBinContent(45,2);
   Shower_E__5->SetBinContent(46,4);
   Shower_E__5->SetBinContent(47,8);
   Shower_E__5->SetBinContent(48,22);
   Shower_E__5->SetBinContent(49,36);
   Shower_E__5->SetBinContent(50,53);
   Shower_E__5->SetBinContent(51,74);
   Shower_E__5->SetBinContent(52,95);
   Shower_E__5->SetBinContent(53,103);
   Shower_E__5->SetBinContent(54,116);
   Shower_E__5->SetBinContent(55,112);
   Shower_E__5->SetBinContent(56,100);
   Shower_E__5->SetBinContent(57,84);
   Shower_E__5->SetBinContent(58,67);
   Shower_E__5->SetBinContent(59,44);
   Shower_E__5->SetBinContent(60,35);
   Shower_E__5->SetBinContent(61,24);
   Shower_E__5->SetBinContent(62,9);
   Shower_E__5->SetBinContent(63,4);
   Shower_E__5->SetBinContent(64,3);
   Shower_E__5->SetBinContent(65,2);
   Shower_E__5->SetEntries(999);
   Shower_E__5->SetStats(0);

   ci = TColor::GetColor("#ff0033");
   Shower_E__5->SetLineColor(ci);
   Shower_E__5->SetLineStyle(2);
   Shower_E__5->SetLineWidth(2);
   Shower_E__5->SetMarkerStyle(20);
   Shower_E__5->SetMarkerSize(1.2);
   Shower_E__5->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__5->GetXaxis()->SetLabelFont(42);
   Shower_E__5->GetXaxis()->SetLabelSize(0.05);
   Shower_E__5->GetXaxis()->SetTitleSize(0.05);
   Shower_E__5->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__5->GetXaxis()->SetTitleFont(42);
   Shower_E__5->GetYaxis()->SetTitle("N positron");
   Shower_E__5->GetYaxis()->SetLabelFont(42);
   Shower_E__5->GetYaxis()->SetLabelSize(0.05);
   Shower_E__5->GetYaxis()->SetTitleSize(0.05);
   Shower_E__5->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__5->GetYaxis()->SetTitleFont(42);
   Shower_E__5->GetZaxis()->SetLabelFont(42);
   Shower_E__5->GetZaxis()->SetLabelSize(0.05);
   Shower_E__5->GetZaxis()->SetTitleSize(0.05);
   Shower_E__5->GetZaxis()->SetTitleOffset(1);
   Shower_E__5->GetZaxis()->SetTitleFont(42);
   Shower_E__5->Draw("same");
   
   TH1D *Shower_E__6 = new TH1D("Shower_E__6","Shower_E",300,0,0.75);
   Shower_E__6->SetBinContent(37,1);
   Shower_E__6->SetBinContent(39,4);
   Shower_E__6->SetBinContent(40,5);
   Shower_E__6->SetBinContent(41,13);
   Shower_E__6->SetBinContent(42,30);
   Shower_E__6->SetBinContent(43,52);
   Shower_E__6->SetBinContent(44,75);
   Shower_E__6->SetBinContent(45,94);
   Shower_E__6->SetBinContent(46,129);
   Shower_E__6->SetBinContent(47,143);
   Shower_E__6->SetBinContent(48,115);
   Shower_E__6->SetBinContent(49,104);
   Shower_E__6->SetBinContent(50,77);
   Shower_E__6->SetBinContent(51,62);
   Shower_E__6->SetBinContent(52,50);
   Shower_E__6->SetBinContent(53,27);
   Shower_E__6->SetBinContent(54,12);
   Shower_E__6->SetBinContent(55,3);
   Shower_E__6->SetBinContent(56,3);
   Shower_E__6->SetEntries(999);
   Shower_E__6->SetStats(0);

   ci = TColor::GetColor("#ff0033");
   Shower_E__6->SetLineColor(ci);
   Shower_E__6->SetLineWidth(2);
   Shower_E__6->SetMarkerStyle(20);
   Shower_E__6->SetMarkerSize(1.2);
   Shower_E__6->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__6->GetXaxis()->SetLabelFont(42);
   Shower_E__6->GetXaxis()->SetLabelSize(0.05);
   Shower_E__6->GetXaxis()->SetTitleSize(0.05);
   Shower_E__6->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__6->GetXaxis()->SetTitleFont(42);
   Shower_E__6->GetYaxis()->SetTitle("N positron");
   Shower_E__6->GetYaxis()->SetLabelFont(42);
   Shower_E__6->GetYaxis()->SetLabelSize(0.05);
   Shower_E__6->GetYaxis()->SetTitleSize(0.05);
   Shower_E__6->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__6->GetYaxis()->SetTitleFont(42);
   Shower_E__6->GetZaxis()->SetLabelFont(42);
   Shower_E__6->GetZaxis()->SetLabelSize(0.05);
   Shower_E__6->GetZaxis()->SetTitleSize(0.05);
   Shower_E__6->GetZaxis()->SetTitleOffset(1);
   Shower_E__6->GetZaxis()->SetTitleFont(42);
   Shower_E__6->Draw("same");
   
   TH1D *Shower_E__7 = new TH1D("Shower_E__7","Shower_E",300,0,0.75);
   Shower_E__7->SetBinContent(33,1);
   Shower_E__7->SetBinContent(34,5);
   Shower_E__7->SetBinContent(35,9);
   Shower_E__7->SetBinContent(36,16);
   Shower_E__7->SetBinContent(37,36);
   Shower_E__7->SetBinContent(38,59);
   Shower_E__7->SetBinContent(39,94);
   Shower_E__7->SetBinContent(40,90);
   Shower_E__7->SetBinContent(41,147);
   Shower_E__7->SetBinContent(42,131);
   Shower_E__7->SetBinContent(43,127);
   Shower_E__7->SetBinContent(44,107);
   Shower_E__7->SetBinContent(45,78);
   Shower_E__7->SetBinContent(46,53);
   Shower_E__7->SetBinContent(47,23);
   Shower_E__7->SetBinContent(48,14);
   Shower_E__7->SetBinContent(49,5);
   Shower_E__7->SetBinContent(50,1);
   Shower_E__7->SetBinContent(51,2);
   Shower_E__7->SetBinContent(52,1);
   Shower_E__7->SetEntries(999);
   Shower_E__7->SetStats(0);

   ci = TColor::GetColor("#cc0000");
   Shower_E__7->SetLineColor(ci);
   Shower_E__7->SetLineStyle(2);
   Shower_E__7->SetLineWidth(2);
   Shower_E__7->SetMarkerStyle(20);
   Shower_E__7->SetMarkerSize(1.2);
   Shower_E__7->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__7->GetXaxis()->SetLabelFont(42);
   Shower_E__7->GetXaxis()->SetLabelSize(0.05);
   Shower_E__7->GetXaxis()->SetTitleSize(0.05);
   Shower_E__7->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__7->GetXaxis()->SetTitleFont(42);
   Shower_E__7->GetYaxis()->SetTitle("N positron");
   Shower_E__7->GetYaxis()->SetLabelFont(42);
   Shower_E__7->GetYaxis()->SetLabelSize(0.05);
   Shower_E__7->GetYaxis()->SetTitleSize(0.05);
   Shower_E__7->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__7->GetYaxis()->SetTitleFont(42);
   Shower_E__7->GetZaxis()->SetLabelFont(42);
   Shower_E__7->GetZaxis()->SetLabelSize(0.05);
   Shower_E__7->GetZaxis()->SetTitleSize(0.05);
   Shower_E__7->GetZaxis()->SetTitleOffset(1);
   Shower_E__7->GetZaxis()->SetTitleFont(42);
   Shower_E__7->Draw("same");
   
   TH1D *Shower_E__8 = new TH1D("Shower_E__8","Shower_E",300,0,0.75);
   Shower_E__8->SetBinContent(30,2);
   Shower_E__8->SetBinContent(31,3);
   Shower_E__8->SetBinContent(32,10);
   Shower_E__8->SetBinContent(33,20);
   Shower_E__8->SetBinContent(34,52);
   Shower_E__8->SetBinContent(35,70);
   Shower_E__8->SetBinContent(36,95);
   Shower_E__8->SetBinContent(37,121);
   Shower_E__8->SetBinContent(38,163);
   Shower_E__8->SetBinContent(39,129);
   Shower_E__8->SetBinContent(40,133);
   Shower_E__8->SetBinContent(41,94);
   Shower_E__8->SetBinContent(42,54);
   Shower_E__8->SetBinContent(43,30);
   Shower_E__8->SetBinContent(44,11);
   Shower_E__8->SetBinContent(45,8);
   Shower_E__8->SetBinContent(46,2);
   Shower_E__8->SetBinContent(47,2);
   Shower_E__8->SetEntries(999);
   Shower_E__8->SetStats(0);

   ci = TColor::GetColor("#cc0000");
   Shower_E__8->SetLineColor(ci);
   Shower_E__8->SetLineWidth(2);
   Shower_E__8->SetMarkerStyle(20);
   Shower_E__8->SetMarkerSize(1.2);
   Shower_E__8->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__8->GetXaxis()->SetLabelFont(42);
   Shower_E__8->GetXaxis()->SetLabelSize(0.05);
   Shower_E__8->GetXaxis()->SetTitleSize(0.05);
   Shower_E__8->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__8->GetXaxis()->SetTitleFont(42);
   Shower_E__8->GetYaxis()->SetTitle("N positron");
   Shower_E__8->GetYaxis()->SetLabelFont(42);
   Shower_E__8->GetYaxis()->SetLabelSize(0.05);
   Shower_E__8->GetYaxis()->SetTitleSize(0.05);
   Shower_E__8->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__8->GetYaxis()->SetTitleFont(42);
   Shower_E__8->GetZaxis()->SetLabelFont(42);
   Shower_E__8->GetZaxis()->SetLabelSize(0.05);
   Shower_E__8->GetZaxis()->SetTitleSize(0.05);
   Shower_E__8->GetZaxis()->SetTitleOffset(1);
   Shower_E__8->GetZaxis()->SetTitleFont(42);
   Shower_E__8->Draw("same");
   
   TH1D *Shower_E__9 = new TH1D("Shower_E__9","Shower_E",300,0,0.75);
   Shower_E__9->SetBinContent(23,1);
   Shower_E__9->SetBinContent(24,5);
   Shower_E__9->SetBinContent(25,12);
   Shower_E__9->SetBinContent(26,28);
   Shower_E__9->SetBinContent(27,59);
   Shower_E__9->SetBinContent(28,121);
   Shower_E__9->SetBinContent(29,133);
   Shower_E__9->SetBinContent(30,176);
   Shower_E__9->SetBinContent(31,140);
   Shower_E__9->SetBinContent(32,127);
   Shower_E__9->SetBinContent(33,92);
   Shower_E__9->SetBinContent(34,55);
   Shower_E__9->SetBinContent(35,22);
   Shower_E__9->SetBinContent(36,18);
   Shower_E__9->SetBinContent(37,8);
   Shower_E__9->SetBinContent(38,2);
   Shower_E__9->SetEntries(999);
   Shower_E__9->SetStats(0);

   ci = TColor::GetColor("#ff9900");
   Shower_E__9->SetLineColor(ci);
   Shower_E__9->SetLineStyle(2);
   Shower_E__9->SetLineWidth(2);
   Shower_E__9->SetMarkerStyle(20);
   Shower_E__9->SetMarkerSize(1.2);
   Shower_E__9->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__9->GetXaxis()->SetLabelFont(42);
   Shower_E__9->GetXaxis()->SetLabelSize(0.05);
   Shower_E__9->GetXaxis()->SetTitleSize(0.05);
   Shower_E__9->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__9->GetXaxis()->SetTitleFont(42);
   Shower_E__9->GetYaxis()->SetTitle("N positron");
   Shower_E__9->GetYaxis()->SetLabelFont(42);
   Shower_E__9->GetYaxis()->SetLabelSize(0.05);
   Shower_E__9->GetYaxis()->SetTitleSize(0.05);
   Shower_E__9->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__9->GetYaxis()->SetTitleFont(42);
   Shower_E__9->GetZaxis()->SetLabelFont(42);
   Shower_E__9->GetZaxis()->SetLabelSize(0.05);
   Shower_E__9->GetZaxis()->SetTitleSize(0.05);
   Shower_E__9->GetZaxis()->SetTitleOffset(1);
   Shower_E__9->GetZaxis()->SetTitleFont(42);
   Shower_E__9->Draw("same");
   
   TH1D *Shower_E__10 = new TH1D("Shower_E__10","Shower_E",300,0,0.75);
   Shower_E__10->SetBinContent(22,1);
   Shower_E__10->SetBinContent(23,6);
   Shower_E__10->SetBinContent(24,21);
   Shower_E__10->SetBinContent(25,31);
   Shower_E__10->SetBinContent(26,91);
   Shower_E__10->SetBinContent(27,138);
   Shower_E__10->SetBinContent(28,155);
   Shower_E__10->SetBinContent(29,176);
   Shower_E__10->SetBinContent(30,131);
   Shower_E__10->SetBinContent(31,112);
   Shower_E__10->SetBinContent(32,67);
   Shower_E__10->SetBinContent(33,34);
   Shower_E__10->SetBinContent(34,22);
   Shower_E__10->SetBinContent(35,9);
   Shower_E__10->SetBinContent(36,5);
   Shower_E__10->SetEntries(999);
   Shower_E__10->SetStats(0);

   ci = TColor::GetColor("#ff9900");
   Shower_E__10->SetLineColor(ci);
   Shower_E__10->SetLineWidth(2);
   Shower_E__10->SetMarkerStyle(20);
   Shower_E__10->SetMarkerSize(1.2);
   Shower_E__10->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__10->GetXaxis()->SetLabelFont(42);
   Shower_E__10->GetXaxis()->SetLabelSize(0.05);
   Shower_E__10->GetXaxis()->SetTitleSize(0.05);
   Shower_E__10->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__10->GetXaxis()->SetTitleFont(42);
   Shower_E__10->GetYaxis()->SetTitle("N positron");
   Shower_E__10->GetYaxis()->SetLabelFont(42);
   Shower_E__10->GetYaxis()->SetLabelSize(0.05);
   Shower_E__10->GetYaxis()->SetTitleSize(0.05);
   Shower_E__10->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__10->GetYaxis()->SetTitleFont(42);
   Shower_E__10->GetZaxis()->SetLabelFont(42);
   Shower_E__10->GetZaxis()->SetLabelSize(0.05);
   Shower_E__10->GetZaxis()->SetTitleSize(0.05);
   Shower_E__10->GetZaxis()->SetTitleOffset(1);
   Shower_E__10->GetZaxis()->SetTitleFont(42);
   Shower_E__10->Draw("same");
   
   TH1D *Shower_E__11 = new TH1D("Shower_E__11","Shower_E",300,0,0.75);
   Shower_E__11->SetBinContent(15,3);
   Shower_E__11->SetBinContent(16,19);
   Shower_E__11->SetBinContent(17,65);
   Shower_E__11->SetBinContent(18,139);
   Shower_E__11->SetBinContent(19,195);
   Shower_E__11->SetBinContent(20,208);
   Shower_E__11->SetBinContent(21,157);
   Shower_E__11->SetBinContent(22,114);
   Shower_E__11->SetBinContent(23,56);
   Shower_E__11->SetBinContent(24,32);
   Shower_E__11->SetBinContent(25,7);
   Shower_E__11->SetBinContent(26,3);
   Shower_E__11->SetBinContent(27,1);
   Shower_E__11->SetEntries(999);
   Shower_E__11->SetStats(0);

   ci = TColor::GetColor("#33ff33");
   Shower_E__11->SetLineColor(ci);
   Shower_E__11->SetLineStyle(2);
   Shower_E__11->SetLineWidth(2);
   Shower_E__11->SetMarkerStyle(20);
   Shower_E__11->SetMarkerSize(1.2);
   Shower_E__11->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__11->GetXaxis()->SetLabelFont(42);
   Shower_E__11->GetXaxis()->SetLabelSize(0.05);
   Shower_E__11->GetXaxis()->SetTitleSize(0.05);
   Shower_E__11->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__11->GetXaxis()->SetTitleFont(42);
   Shower_E__11->GetYaxis()->SetTitle("N positron");
   Shower_E__11->GetYaxis()->SetLabelFont(42);
   Shower_E__11->GetYaxis()->SetLabelSize(0.05);
   Shower_E__11->GetYaxis()->SetTitleSize(0.05);
   Shower_E__11->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__11->GetYaxis()->SetTitleFont(42);
   Shower_E__11->GetZaxis()->SetLabelFont(42);
   Shower_E__11->GetZaxis()->SetLabelSize(0.05);
   Shower_E__11->GetZaxis()->SetTitleSize(0.05);
   Shower_E__11->GetZaxis()->SetTitleOffset(1);
   Shower_E__11->GetZaxis()->SetTitleFont(42);
   Shower_E__11->Draw("same");
   
   TH1D *Shower_E__12 = new TH1D("Shower_E__12","Shower_E",300,0,0.75);
   Shower_E__12->SetBinContent(14,2);
   Shower_E__12->SetBinContent(15,9);
   Shower_E__12->SetBinContent(16,40);
   Shower_E__12->SetBinContent(17,111);
   Shower_E__12->SetBinContent(18,179);
   Shower_E__12->SetBinContent(19,226);
   Shower_E__12->SetBinContent(20,166);
   Shower_E__12->SetBinContent(21,132);
   Shower_E__12->SetBinContent(22,78);
   Shower_E__12->SetBinContent(23,36);
   Shower_E__12->SetBinContent(24,16);
   Shower_E__12->SetBinContent(25,2);
   Shower_E__12->SetBinContent(26,2);
   Shower_E__12->SetEntries(999);
   Shower_E__12->SetStats(0);

   ci = TColor::GetColor("#33ff33");
   Shower_E__12->SetLineColor(ci);
   Shower_E__12->SetLineWidth(2);
   Shower_E__12->SetMarkerStyle(20);
   Shower_E__12->SetMarkerSize(1.2);
   Shower_E__12->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__12->GetXaxis()->SetLabelFont(42);
   Shower_E__12->GetXaxis()->SetLabelSize(0.05);
   Shower_E__12->GetXaxis()->SetTitleSize(0.05);
   Shower_E__12->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__12->GetXaxis()->SetTitleFont(42);
   Shower_E__12->GetYaxis()->SetTitle("N positron");
   Shower_E__12->GetYaxis()->SetLabelFont(42);
   Shower_E__12->GetYaxis()->SetLabelSize(0.05);
   Shower_E__12->GetYaxis()->SetTitleSize(0.05);
   Shower_E__12->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__12->GetYaxis()->SetTitleFont(42);
   Shower_E__12->GetZaxis()->SetLabelFont(42);
   Shower_E__12->GetZaxis()->SetLabelSize(0.05);
   Shower_E__12->GetZaxis()->SetTitleSize(0.05);
   Shower_E__12->GetZaxis()->SetTitleOffset(1);
   Shower_E__12->GetZaxis()->SetTitleFont(42);
   Shower_E__12->Draw("same");
   
   TH1D *Shower_E__13 = new TH1D("Shower_E__13","Shower_E",300,0,0.75);
   Shower_E__13->SetBinContent(6,1);
   Shower_E__13->SetBinContent(7,16);
   Shower_E__13->SetBinContent(8,106);
   Shower_E__13->SetBinContent(9,246);
   Shower_E__13->SetBinContent(10,284);
   Shower_E__13->SetBinContent(11,197);
   Shower_E__13->SetBinContent(12,104);
   Shower_E__13->SetBinContent(13,38);
   Shower_E__13->SetBinContent(14,6);
   Shower_E__13->SetBinContent(15,1);
   Shower_E__13->SetEntries(999);
   Shower_E__13->SetStats(0);

   ci = TColor::GetColor("#006600");
   Shower_E__13->SetLineColor(ci);
   Shower_E__13->SetLineStyle(2);
   Shower_E__13->SetLineWidth(2);
   Shower_E__13->SetMarkerStyle(20);
   Shower_E__13->SetMarkerSize(1.2);
   Shower_E__13->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__13->GetXaxis()->SetLabelFont(42);
   Shower_E__13->GetXaxis()->SetLabelSize(0.05);
   Shower_E__13->GetXaxis()->SetTitleSize(0.05);
   Shower_E__13->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__13->GetXaxis()->SetTitleFont(42);
   Shower_E__13->GetYaxis()->SetTitle("N positron");
   Shower_E__13->GetYaxis()->SetLabelFont(42);
   Shower_E__13->GetYaxis()->SetLabelSize(0.05);
   Shower_E__13->GetYaxis()->SetTitleSize(0.05);
   Shower_E__13->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__13->GetYaxis()->SetTitleFont(42);
   Shower_E__13->GetZaxis()->SetLabelFont(42);
   Shower_E__13->GetZaxis()->SetLabelSize(0.05);
   Shower_E__13->GetZaxis()->SetTitleSize(0.05);
   Shower_E__13->GetZaxis()->SetTitleOffset(1);
   Shower_E__13->GetZaxis()->SetTitleFont(42);
   Shower_E__13->Draw("same");
   
   TH1D *Shower_E__14 = new TH1D("Shower_E__14","Shower_E",300,0,0.75);
   Shower_E__14->SetBinContent(6,1);
   Shower_E__14->SetBinContent(7,22);
   Shower_E__14->SetBinContent(8,111);
   Shower_E__14->SetBinContent(9,256);
   Shower_E__14->SetBinContent(10,288);
   Shower_E__14->SetBinContent(11,189);
   Shower_E__14->SetBinContent(12,89);
   Shower_E__14->SetBinContent(13,37);
   Shower_E__14->SetBinContent(14,5);
   Shower_E__14->SetBinContent(15,1);
   Shower_E__14->SetEntries(999);
   Shower_E__14->SetStats(0);

   ci = TColor::GetColor("#006600");
   Shower_E__14->SetLineColor(ci);
   Shower_E__14->SetLineWidth(2);
   Shower_E__14->SetMarkerStyle(20);
   Shower_E__14->SetMarkerSize(1.2);
   Shower_E__14->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__14->GetXaxis()->SetLabelFont(42);
   Shower_E__14->GetXaxis()->SetLabelSize(0.05);
   Shower_E__14->GetXaxis()->SetTitleSize(0.05);
   Shower_E__14->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__14->GetXaxis()->SetTitleFont(42);
   Shower_E__14->GetYaxis()->SetTitle("N positron");
   Shower_E__14->GetYaxis()->SetLabelFont(42);
   Shower_E__14->GetYaxis()->SetLabelSize(0.05);
   Shower_E__14->GetYaxis()->SetTitleSize(0.05);
   Shower_E__14->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__14->GetYaxis()->SetTitleFont(42);
   Shower_E__14->GetZaxis()->SetLabelFont(42);
   Shower_E__14->GetZaxis()->SetLabelSize(0.05);
   Shower_E__14->GetZaxis()->SetTitleSize(0.05);
   Shower_E__14->GetZaxis()->SetTitleOffset(1);
   Shower_E__14->GetZaxis()->SetTitleFont(42);
   Shower_E__14->Draw("same");
   
   TLegend *leg = new TLegend(0.55,0.5,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Shower_E","14 GeV e^{+} with bkg from beam","l");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","14 GeV e^{+} without bkg from beam","l");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","12 GeV e^{+} with bkg from beam","l");

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","12 GeV e^{+} without bkg from beam","l");

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","10 GeV e^{+} with bkg from beam","l");

   ci = TColor::GetColor("#ff0033");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","10 GeV e^{+} without bkg from beam","l");

   ci = TColor::GetColor("#ff0033");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","8 GeV e^{+} with bkg from beam","l");

   ci = TColor::GetColor("#cc0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","8 GeV e^{+} without bkg from beam","l");

   ci = TColor::GetColor("#cc0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","6 GeV e^{+} with bkg from beam","l");

   ci = TColor::GetColor("#ff9900");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","6 GeV e^{+} without bkg from beam","l");

   ci = TColor::GetColor("#ff9900");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","4 GeV e^{+} with bkg from beam","l");

   ci = TColor::GetColor("#33ff33");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","4 GeV e^{+} without bkg from beam","l");

   ci = TColor::GetColor("#33ff33");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","2 GeV e^{+} with bkg from beam","l");

   ci = TColor::GetColor("#006600");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","2 GeV e^{+} without bkg from beam","l");

   ci = TColor::GetColor("#006600");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.2,0.85,"LUXE");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2982959,0.85,"CDR");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.8,"Calorimeter - e-laser");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetLineWidth(2);
   tex->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
