void Calorimeter_glaser_ShowerEnergyDeposition()
{
//=========Macro generated from canvas: c1/c1
//=========  (Wed Mar 10 12:36:50 2021) by ROOT version 6.22/06
   TCanvas *c1 = new TCanvas("c1", "c1",10,32,700,500);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->Range(-0.05063291,-81.01265,0.2658228,425.3165);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.16);
   c1->SetRightMargin(0.05);
   c1->SetTopMargin(0.05);
   c1->SetBottomMargin(0.16);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderMode(0);
   
   TH1D *Shower_E__1 = new TH1D("Shower_E__1","Shower_E",300,0,0.75);
   Shower_E__1->SetBinContent(46,1);
   Shower_E__1->SetBinContent(59,1);
   Shower_E__1->SetBinContent(62,1);
   Shower_E__1->SetBinContent(63,1);
   Shower_E__1->SetBinContent(64,2);
   Shower_E__1->SetBinContent(65,4);
   Shower_E__1->SetBinContent(66,1);
   Shower_E__1->SetBinContent(67,13);
   Shower_E__1->SetBinContent(68,19);
   Shower_E__1->SetBinContent(69,21);
   Shower_E__1->SetBinContent(70,28);
   Shower_E__1->SetBinContent(71,44);
   Shower_E__1->SetBinContent(72,51);
   Shower_E__1->SetBinContent(73,55);
   Shower_E__1->SetBinContent(74,87);
   Shower_E__1->SetBinContent(75,96);
   Shower_E__1->SetBinContent(76,73);
   Shower_E__1->SetBinContent(77,100);
   Shower_E__1->SetBinContent(78,94);
   Shower_E__1->SetBinContent(79,74);
   Shower_E__1->SetBinContent(80,67);
   Shower_E__1->SetBinContent(81,49);
   Shower_E__1->SetBinContent(82,34);
   Shower_E__1->SetBinContent(83,29);
   Shower_E__1->SetBinContent(84,21);
   Shower_E__1->SetBinContent(85,10);
   Shower_E__1->SetBinContent(86,10);
   Shower_E__1->SetBinContent(87,3);
   Shower_E__1->SetBinContent(88,2);
   Shower_E__1->SetBinContent(89,2);
   Shower_E__1->SetBinContent(90,4);
   Shower_E__1->SetBinContent(91,1);
   Shower_E__1->SetBinContent(94,1);
   Shower_E__1->SetMinimum(0);
   Shower_E__1->SetMaximum(400);
   Shower_E__1->SetEntries(999);
   Shower_E__1->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   Shower_E__1->SetLineColor(ci);
   Shower_E__1->SetLineStyle(2);
   Shower_E__1->SetLineWidth(2);
   Shower_E__1->SetMarkerStyle(20);
   Shower_E__1->SetMarkerSize(1.2);
   Shower_E__1->GetXaxis()->SetTitle("Shower Energy Deposition (GeV)");
   Shower_E__1->GetXaxis()->SetRange(1,100);
   Shower_E__1->GetXaxis()->SetLabelFont(42);
   Shower_E__1->GetXaxis()->SetLabelSize(0.05);
   Shower_E__1->GetXaxis()->SetTitleSize(0.05);
   Shower_E__1->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__1->GetXaxis()->SetTitleFont(42);
   Shower_E__1->GetYaxis()->SetTitle("Arbirtary Units");
   Shower_E__1->GetYaxis()->SetLabelFont(42);
   Shower_E__1->GetYaxis()->SetLabelSize(0.05);
   Shower_E__1->GetYaxis()->SetTitleSize(0.05);
   Shower_E__1->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__1->GetYaxis()->SetTitleFont(42);
   Shower_E__1->GetZaxis()->SetLabelFont(42);
   Shower_E__1->GetZaxis()->SetLabelSize(0.05);
   Shower_E__1->GetZaxis()->SetTitleSize(0.05);
   Shower_E__1->GetZaxis()->SetTitleOffset(1);
   Shower_E__1->GetZaxis()->SetTitleFont(42);
   Shower_E__1->Draw("");
   
   TH1D *Shower_E__2 = new TH1D("Shower_E__2","Shower_E",300,0,0.75);
   Shower_E__2->SetBinContent(41,1);
   Shower_E__2->SetBinContent(54,1);
   Shower_E__2->SetBinContent(55,1);
   Shower_E__2->SetBinContent(56,2);
   Shower_E__2->SetBinContent(57,4);
   Shower_E__2->SetBinContent(58,12);
   Shower_E__2->SetBinContent(59,8);
   Shower_E__2->SetBinContent(60,28);
   Shower_E__2->SetBinContent(61,48);
   Shower_E__2->SetBinContent(62,44);
   Shower_E__2->SetBinContent(63,77);
   Shower_E__2->SetBinContent(64,95);
   Shower_E__2->SetBinContent(65,83);
   Shower_E__2->SetBinContent(66,105);
   Shower_E__2->SetBinContent(67,102);
   Shower_E__2->SetBinContent(68,122);
   Shower_E__2->SetBinContent(69,97);
   Shower_E__2->SetBinContent(70,66);
   Shower_E__2->SetBinContent(71,46);
   Shower_E__2->SetBinContent(72,31);
   Shower_E__2->SetBinContent(73,10);
   Shower_E__2->SetBinContent(74,8);
   Shower_E__2->SetBinContent(75,4);
   Shower_E__2->SetBinContent(76,2);
   Shower_E__2->SetBinContent(77,1);
   Shower_E__2->SetBinContent(78,1);
   Shower_E__2->SetEntries(999);
   Shower_E__2->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   Shower_E__2->SetLineColor(ci);
   Shower_E__2->SetLineWidth(2);
   Shower_E__2->SetMarkerStyle(20);
   Shower_E__2->SetMarkerSize(1.2);
   Shower_E__2->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__2->GetXaxis()->SetLabelFont(42);
   Shower_E__2->GetXaxis()->SetLabelSize(0.05);
   Shower_E__2->GetXaxis()->SetTitleSize(0.05);
   Shower_E__2->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__2->GetXaxis()->SetTitleFont(42);
   Shower_E__2->GetYaxis()->SetTitle("N positron");
   Shower_E__2->GetYaxis()->SetLabelFont(42);
   Shower_E__2->GetYaxis()->SetLabelSize(0.05);
   Shower_E__2->GetYaxis()->SetTitleSize(0.05);
   Shower_E__2->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__2->GetYaxis()->SetTitleFont(42);
   Shower_E__2->GetZaxis()->SetLabelFont(42);
   Shower_E__2->GetZaxis()->SetLabelSize(0.05);
   Shower_E__2->GetZaxis()->SetTitleSize(0.05);
   Shower_E__2->GetZaxis()->SetTitleOffset(1);
   Shower_E__2->GetZaxis()->SetTitleFont(42);
   Shower_E__2->Draw("same");
   
   TH1D *Shower_E__3 = new TH1D("Shower_E__3","Shower_E",300,0,0.75);
   Shower_E__3->SetBinContent(51,1);
   Shower_E__3->SetBinContent(52,2);
   Shower_E__3->SetBinContent(53,2);
   Shower_E__3->SetBinContent(54,4);
   Shower_E__3->SetBinContent(55,21);
   Shower_E__3->SetBinContent(56,12);
   Shower_E__3->SetBinContent(57,37);
   Shower_E__3->SetBinContent(58,57);
   Shower_E__3->SetBinContent(59,78);
   Shower_E__3->SetBinContent(60,100);
   Shower_E__3->SetBinContent(61,90);
   Shower_E__3->SetBinContent(62,113);
   Shower_E__3->SetBinContent(63,106);
   Shower_E__3->SetBinContent(64,110);
   Shower_E__3->SetBinContent(65,86);
   Shower_E__3->SetBinContent(66,60);
   Shower_E__3->SetBinContent(67,42);
   Shower_E__3->SetBinContent(68,26);
   Shower_E__3->SetBinContent(69,20);
   Shower_E__3->SetBinContent(70,14);
   Shower_E__3->SetBinContent(71,10);
   Shower_E__3->SetBinContent(72,3);
   Shower_E__3->SetBinContent(73,3);
   Shower_E__3->SetBinContent(75,1);
   Shower_E__3->SetBinContent(76,1);
   Shower_E__3->SetEntries(999);
   Shower_E__3->SetStats(0);

   ci = TColor::GetColor("#ff00ff");
   Shower_E__3->SetLineColor(ci);
   Shower_E__3->SetLineStyle(2);
   Shower_E__3->SetLineWidth(2);
   Shower_E__3->SetMarkerStyle(20);
   Shower_E__3->SetMarkerSize(1.2);
   Shower_E__3->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__3->GetXaxis()->SetLabelFont(42);
   Shower_E__3->GetXaxis()->SetLabelSize(0.05);
   Shower_E__3->GetXaxis()->SetTitleSize(0.05);
   Shower_E__3->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__3->GetXaxis()->SetTitleFont(42);
   Shower_E__3->GetYaxis()->SetTitle("N positron");
   Shower_E__3->GetYaxis()->SetLabelFont(42);
   Shower_E__3->GetYaxis()->SetLabelSize(0.05);
   Shower_E__3->GetYaxis()->SetTitleSize(0.05);
   Shower_E__3->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__3->GetYaxis()->SetTitleFont(42);
   Shower_E__3->GetZaxis()->SetLabelFont(42);
   Shower_E__3->GetZaxis()->SetLabelSize(0.05);
   Shower_E__3->GetZaxis()->SetTitleSize(0.05);
   Shower_E__3->GetZaxis()->SetTitleOffset(1);
   Shower_E__3->GetZaxis()->SetTitleFont(42);
   Shower_E__3->Draw("same");
   
   TH1D *Shower_E__4 = new TH1D("Shower_E__4","Shower_E",300,0,0.75);
   Shower_E__4->SetBinContent(46,1);
   Shower_E__4->SetBinContent(47,1);
   Shower_E__4->SetBinContent(48,3);
   Shower_E__4->SetBinContent(49,6);
   Shower_E__4->SetBinContent(50,8);
   Shower_E__4->SetBinContent(51,14);
   Shower_E__4->SetBinContent(52,39);
   Shower_E__4->SetBinContent(53,70);
   Shower_E__4->SetBinContent(54,85);
   Shower_E__4->SetBinContent(55,108);
   Shower_E__4->SetBinContent(56,122);
   Shower_E__4->SetBinContent(57,110);
   Shower_E__4->SetBinContent(58,120);
   Shower_E__4->SetBinContent(59,101);
   Shower_E__4->SetBinContent(60,75);
   Shower_E__4->SetBinContent(61,47);
   Shower_E__4->SetBinContent(62,40);
   Shower_E__4->SetBinContent(63,22);
   Shower_E__4->SetBinContent(64,11);
   Shower_E__4->SetBinContent(65,9);
   Shower_E__4->SetBinContent(66,5);
   Shower_E__4->SetBinContent(67,1);
   Shower_E__4->SetBinContent(68,1);
   Shower_E__4->SetEntries(999);
   Shower_E__4->SetStats(0);

   ci = TColor::GetColor("#ff00ff");
   Shower_E__4->SetLineColor(ci);
   Shower_E__4->SetLineWidth(2);
   Shower_E__4->SetMarkerStyle(20);
   Shower_E__4->SetMarkerSize(1.2);
   Shower_E__4->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__4->GetXaxis()->SetLabelFont(42);
   Shower_E__4->GetXaxis()->SetLabelSize(0.05);
   Shower_E__4->GetXaxis()->SetTitleSize(0.05);
   Shower_E__4->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__4->GetXaxis()->SetTitleFont(42);
   Shower_E__4->GetYaxis()->SetTitle("N positron");
   Shower_E__4->GetYaxis()->SetLabelFont(42);
   Shower_E__4->GetYaxis()->SetLabelSize(0.05);
   Shower_E__4->GetYaxis()->SetTitleSize(0.05);
   Shower_E__4->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__4->GetYaxis()->SetTitleFont(42);
   Shower_E__4->GetZaxis()->SetLabelFont(42);
   Shower_E__4->GetZaxis()->SetLabelSize(0.05);
   Shower_E__4->GetZaxis()->SetTitleSize(0.05);
   Shower_E__4->GetZaxis()->SetTitleOffset(1);
   Shower_E__4->GetZaxis()->SetTitleFont(42);
   Shower_E__4->Draw("same");
   
   TH1D *Shower_E__5 = new TH1D("Shower_E__5","Shower_E",300,0,0.75);
   Shower_E__5->SetBinContent(42,3);
   Shower_E__5->SetBinContent(43,4);
   Shower_E__5->SetBinContent(44,11);
   Shower_E__5->SetBinContent(45,21);
   Shower_E__5->SetBinContent(46,47);
   Shower_E__5->SetBinContent(47,63);
   Shower_E__5->SetBinContent(48,80);
   Shower_E__5->SetBinContent(49,96);
   Shower_E__5->SetBinContent(50,131);
   Shower_E__5->SetBinContent(51,143);
   Shower_E__5->SetBinContent(52,114);
   Shower_E__5->SetBinContent(53,83);
   Shower_E__5->SetBinContent(54,79);
   Shower_E__5->SetBinContent(55,50);
   Shower_E__5->SetBinContent(56,36);
   Shower_E__5->SetBinContent(57,18);
   Shower_E__5->SetBinContent(58,12);
   Shower_E__5->SetBinContent(59,4);
   Shower_E__5->SetBinContent(60,2);
   Shower_E__5->SetBinContent(61,1);
   Shower_E__5->SetBinContent(62,1);
   Shower_E__5->SetEntries(999);
   Shower_E__5->SetStats(0);

   ci = TColor::GetColor("#ff0033");
   Shower_E__5->SetLineColor(ci);
   Shower_E__5->SetLineStyle(2);
   Shower_E__5->SetLineWidth(2);
   Shower_E__5->SetMarkerStyle(20);
   Shower_E__5->SetMarkerSize(1.2);
   Shower_E__5->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__5->GetXaxis()->SetLabelFont(42);
   Shower_E__5->GetXaxis()->SetLabelSize(0.05);
   Shower_E__5->GetXaxis()->SetTitleSize(0.05);
   Shower_E__5->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__5->GetXaxis()->SetTitleFont(42);
   Shower_E__5->GetYaxis()->SetTitle("N positron");
   Shower_E__5->GetYaxis()->SetLabelFont(42);
   Shower_E__5->GetYaxis()->SetLabelSize(0.05);
   Shower_E__5->GetYaxis()->SetTitleSize(0.05);
   Shower_E__5->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__5->GetYaxis()->SetTitleFont(42);
   Shower_E__5->GetZaxis()->SetLabelFont(42);
   Shower_E__5->GetZaxis()->SetLabelSize(0.05);
   Shower_E__5->GetZaxis()->SetTitleSize(0.05);
   Shower_E__5->GetZaxis()->SetTitleOffset(1);
   Shower_E__5->GetZaxis()->SetTitleFont(42);
   Shower_E__5->Draw("same");
   
   TH1D *Shower_E__6 = new TH1D("Shower_E__6","Shower_E",300,0,0.75);
   Shower_E__6->SetBinContent(39,3);
   Shower_E__6->SetBinContent(40,4);
   Shower_E__6->SetBinContent(41,8);
   Shower_E__6->SetBinContent(42,21);
   Shower_E__6->SetBinContent(43,43);
   Shower_E__6->SetBinContent(44,67);
   Shower_E__6->SetBinContent(45,79);
   Shower_E__6->SetBinContent(46,97);
   Shower_E__6->SetBinContent(47,144);
   Shower_E__6->SetBinContent(48,130);
   Shower_E__6->SetBinContent(49,133);
   Shower_E__6->SetBinContent(50,89);
   Shower_E__6->SetBinContent(51,78);
   Shower_E__6->SetBinContent(52,52);
   Shower_E__6->SetBinContent(53,22);
   Shower_E__6->SetBinContent(54,15);
   Shower_E__6->SetBinContent(55,9);
   Shower_E__6->SetBinContent(56,1);
   Shower_E__6->SetBinContent(57,2);
   Shower_E__6->SetBinContent(58,1);
   Shower_E__6->SetBinContent(59,1);
   Shower_E__6->SetEntries(999);
   Shower_E__6->SetStats(0);

   ci = TColor::GetColor("#ff0033");
   Shower_E__6->SetLineColor(ci);
   Shower_E__6->SetLineWidth(2);
   Shower_E__6->SetMarkerStyle(20);
   Shower_E__6->SetMarkerSize(1.2);
   Shower_E__6->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__6->GetXaxis()->SetLabelFont(42);
   Shower_E__6->GetXaxis()->SetLabelSize(0.05);
   Shower_E__6->GetXaxis()->SetTitleSize(0.05);
   Shower_E__6->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__6->GetXaxis()->SetTitleFont(42);
   Shower_E__6->GetYaxis()->SetTitle("N positron");
   Shower_E__6->GetYaxis()->SetLabelFont(42);
   Shower_E__6->GetYaxis()->SetLabelSize(0.05);
   Shower_E__6->GetYaxis()->SetTitleSize(0.05);
   Shower_E__6->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__6->GetYaxis()->SetTitleFont(42);
   Shower_E__6->GetZaxis()->SetLabelFont(42);
   Shower_E__6->GetZaxis()->SetLabelSize(0.05);
   Shower_E__6->GetZaxis()->SetTitleSize(0.05);
   Shower_E__6->GetZaxis()->SetTitleOffset(1);
   Shower_E__6->GetZaxis()->SetTitleFont(42);
   Shower_E__6->Draw("same");
   
   TH1D *Shower_E__7 = new TH1D("Shower_E__7","Shower_E",300,0,0.75);
   Shower_E__7->SetBinContent(31,1);
   Shower_E__7->SetBinContent(34,9);
   Shower_E__7->SetBinContent(35,26);
   Shower_E__7->SetBinContent(36,49);
   Shower_E__7->SetBinContent(37,91);
   Shower_E__7->SetBinContent(38,114);
   Shower_E__7->SetBinContent(39,149);
   Shower_E__7->SetBinContent(40,153);
   Shower_E__7->SetBinContent(41,135);
   Shower_E__7->SetBinContent(42,102);
   Shower_E__7->SetBinContent(43,75);
   Shower_E__7->SetBinContent(44,43);
   Shower_E__7->SetBinContent(45,22);
   Shower_E__7->SetBinContent(46,11);
   Shower_E__7->SetBinContent(47,9);
   Shower_E__7->SetBinContent(48,5);
   Shower_E__7->SetBinContent(49,2);
   Shower_E__7->SetBinContent(50,3);
   Shower_E__7->SetEntries(999);
   Shower_E__7->SetStats(0);

   ci = TColor::GetColor("#cc0000");
   Shower_E__7->SetLineColor(ci);
   Shower_E__7->SetLineStyle(2);
   Shower_E__7->SetLineWidth(2);
   Shower_E__7->SetMarkerStyle(20);
   Shower_E__7->SetMarkerSize(1.2);
   Shower_E__7->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__7->GetXaxis()->SetLabelFont(42);
   Shower_E__7->GetXaxis()->SetLabelSize(0.05);
   Shower_E__7->GetXaxis()->SetTitleSize(0.05);
   Shower_E__7->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__7->GetXaxis()->SetTitleFont(42);
   Shower_E__7->GetYaxis()->SetTitle("N positron");
   Shower_E__7->GetYaxis()->SetLabelFont(42);
   Shower_E__7->GetYaxis()->SetLabelSize(0.05);
   Shower_E__7->GetYaxis()->SetTitleSize(0.05);
   Shower_E__7->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__7->GetYaxis()->SetTitleFont(42);
   Shower_E__7->GetZaxis()->SetLabelFont(42);
   Shower_E__7->GetZaxis()->SetLabelSize(0.05);
   Shower_E__7->GetZaxis()->SetTitleSize(0.05);
   Shower_E__7->GetZaxis()->SetTitleOffset(1);
   Shower_E__7->GetZaxis()->SetTitleFont(42);
   Shower_E__7->Draw("same");
   
   TH1D *Shower_E__8 = new TH1D("Shower_E__8","Shower_E",300,0,0.75);
   Shower_E__8->SetBinContent(30,1);
   Shower_E__8->SetBinContent(32,4);
   Shower_E__8->SetBinContent(33,23);
   Shower_E__8->SetBinContent(34,29);
   Shower_E__8->SetBinContent(35,69);
   Shower_E__8->SetBinContent(36,129);
   Shower_E__8->SetBinContent(37,135);
   Shower_E__8->SetBinContent(38,150);
   Shower_E__8->SetBinContent(39,157);
   Shower_E__8->SetBinContent(40,106);
   Shower_E__8->SetBinContent(41,88);
   Shower_E__8->SetBinContent(42,53);
   Shower_E__8->SetBinContent(43,28);
   Shower_E__8->SetBinContent(44,7);
   Shower_E__8->SetBinContent(45,10);
   Shower_E__8->SetBinContent(46,3);
   Shower_E__8->SetBinContent(47,4);
   Shower_E__8->SetBinContent(48,3);
   Shower_E__8->SetEntries(999);
   Shower_E__8->SetStats(0);

   ci = TColor::GetColor("#cc0000");
   Shower_E__8->SetLineColor(ci);
   Shower_E__8->SetLineWidth(2);
   Shower_E__8->SetMarkerStyle(20);
   Shower_E__8->SetMarkerSize(1.2);
   Shower_E__8->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__8->GetXaxis()->SetLabelFont(42);
   Shower_E__8->GetXaxis()->SetLabelSize(0.05);
   Shower_E__8->GetXaxis()->SetTitleSize(0.05);
   Shower_E__8->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__8->GetXaxis()->SetTitleFont(42);
   Shower_E__8->GetYaxis()->SetTitle("N positron");
   Shower_E__8->GetYaxis()->SetLabelFont(42);
   Shower_E__8->GetYaxis()->SetLabelSize(0.05);
   Shower_E__8->GetYaxis()->SetTitleSize(0.05);
   Shower_E__8->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__8->GetYaxis()->SetTitleFont(42);
   Shower_E__8->GetZaxis()->SetLabelFont(42);
   Shower_E__8->GetZaxis()->SetLabelSize(0.05);
   Shower_E__8->GetZaxis()->SetTitleSize(0.05);
   Shower_E__8->GetZaxis()->SetTitleOffset(1);
   Shower_E__8->GetZaxis()->SetTitleFont(42);
   Shower_E__8->Draw("same");
   
   TH1D *Shower_E__9 = new TH1D("Shower_E__9","Shower_E",300,0,0.75);
   Shower_E__9->SetBinContent(23,4);
   Shower_E__9->SetBinContent(24,6);
   Shower_E__9->SetBinContent(25,26);
   Shower_E__9->SetBinContent(26,55);
   Shower_E__9->SetBinContent(27,86);
   Shower_E__9->SetBinContent(28,146);
   Shower_E__9->SetBinContent(29,179);
   Shower_E__9->SetBinContent(30,166);
   Shower_E__9->SetBinContent(31,141);
   Shower_E__9->SetBinContent(32,92);
   Shower_E__9->SetBinContent(33,64);
   Shower_E__9->SetBinContent(34,21);
   Shower_E__9->SetBinContent(35,9);
   Shower_E__9->SetBinContent(36,4);
   Shower_E__9->SetEntries(999);
   Shower_E__9->SetStats(0);

   ci = TColor::GetColor("#ff9900");
   Shower_E__9->SetLineColor(ci);
   Shower_E__9->SetLineStyle(2);
   Shower_E__9->SetLineWidth(2);
   Shower_E__9->SetMarkerStyle(20);
   Shower_E__9->SetMarkerSize(1.2);
   Shower_E__9->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__9->GetXaxis()->SetLabelFont(42);
   Shower_E__9->GetXaxis()->SetLabelSize(0.05);
   Shower_E__9->GetXaxis()->SetTitleSize(0.05);
   Shower_E__9->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__9->GetXaxis()->SetTitleFont(42);
   Shower_E__9->GetYaxis()->SetTitle("N positron");
   Shower_E__9->GetYaxis()->SetLabelFont(42);
   Shower_E__9->GetYaxis()->SetLabelSize(0.05);
   Shower_E__9->GetYaxis()->SetTitleSize(0.05);
   Shower_E__9->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__9->GetYaxis()->SetTitleFont(42);
   Shower_E__9->GetZaxis()->SetLabelFont(42);
   Shower_E__9->GetZaxis()->SetLabelSize(0.05);
   Shower_E__9->GetZaxis()->SetTitleSize(0.05);
   Shower_E__9->GetZaxis()->SetTitleOffset(1);
   Shower_E__9->GetZaxis()->SetTitleFont(42);
   Shower_E__9->Draw("same");
   
   TH1D *Shower_E__10 = new TH1D("Shower_E__10","Shower_E",300,0,0.75);
   Shower_E__10->SetBinContent(22,2);
   Shower_E__10->SetBinContent(23,4);
   Shower_E__10->SetBinContent(24,21);
   Shower_E__10->SetBinContent(25,41);
   Shower_E__10->SetBinContent(26,78);
   Shower_E__10->SetBinContent(27,138);
   Shower_E__10->SetBinContent(28,166);
   Shower_E__10->SetBinContent(29,172);
   Shower_E__10->SetBinContent(30,157);
   Shower_E__10->SetBinContent(31,94);
   Shower_E__10->SetBinContent(32,81);
   Shower_E__10->SetBinContent(33,29);
   Shower_E__10->SetBinContent(34,11);
   Shower_E__10->SetBinContent(35,5);
   Shower_E__10->SetEntries(999);
   Shower_E__10->SetStats(0);

   ci = TColor::GetColor("#ff9900");
   Shower_E__10->SetLineColor(ci);
   Shower_E__10->SetLineWidth(2);
   Shower_E__10->SetMarkerStyle(20);
   Shower_E__10->SetMarkerSize(1.2);
   Shower_E__10->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__10->GetXaxis()->SetLabelFont(42);
   Shower_E__10->GetXaxis()->SetLabelSize(0.05);
   Shower_E__10->GetXaxis()->SetTitleSize(0.05);
   Shower_E__10->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__10->GetXaxis()->SetTitleFont(42);
   Shower_E__10->GetYaxis()->SetTitle("N positron");
   Shower_E__10->GetYaxis()->SetLabelFont(42);
   Shower_E__10->GetYaxis()->SetLabelSize(0.05);
   Shower_E__10->GetYaxis()->SetTitleSize(0.05);
   Shower_E__10->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__10->GetYaxis()->SetTitleFont(42);
   Shower_E__10->GetZaxis()->SetLabelFont(42);
   Shower_E__10->GetZaxis()->SetLabelSize(0.05);
   Shower_E__10->GetZaxis()->SetTitleSize(0.05);
   Shower_E__10->GetZaxis()->SetTitleOffset(1);
   Shower_E__10->GetZaxis()->SetTitleFont(42);
   Shower_E__10->Draw("same");
   
   TH1D *Shower_E__11 = new TH1D("Shower_E__11","Shower_E",300,0,0.75);
   Shower_E__11->SetBinContent(15,5);
   Shower_E__11->SetBinContent(16,27);
   Shower_E__11->SetBinContent(17,70);
   Shower_E__11->SetBinContent(18,117);
   Shower_E__11->SetBinContent(19,195);
   Shower_E__11->SetBinContent(20,209);
   Shower_E__11->SetBinContent(21,169);
   Shower_E__11->SetBinContent(22,107);
   Shower_E__11->SetBinContent(23,51);
   Shower_E__11->SetBinContent(24,27);
   Shower_E__11->SetBinContent(25,15);
   Shower_E__11->SetBinContent(26,6);
   Shower_E__11->SetBinContent(27,1);
   Shower_E__11->SetEntries(999);
   Shower_E__11->SetStats(0);

   ci = TColor::GetColor("#33ff33");
   Shower_E__11->SetLineColor(ci);
   Shower_E__11->SetLineStyle(2);
   Shower_E__11->SetLineWidth(2);
   Shower_E__11->SetMarkerStyle(20);
   Shower_E__11->SetMarkerSize(1.2);
   Shower_E__11->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__11->GetXaxis()->SetLabelFont(42);
   Shower_E__11->GetXaxis()->SetLabelSize(0.05);
   Shower_E__11->GetXaxis()->SetTitleSize(0.05);
   Shower_E__11->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__11->GetXaxis()->SetTitleFont(42);
   Shower_E__11->GetYaxis()->SetTitle("N positron");
   Shower_E__11->GetYaxis()->SetLabelFont(42);
   Shower_E__11->GetYaxis()->SetLabelSize(0.05);
   Shower_E__11->GetYaxis()->SetTitleSize(0.05);
   Shower_E__11->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__11->GetYaxis()->SetTitleFont(42);
   Shower_E__11->GetZaxis()->SetLabelFont(42);
   Shower_E__11->GetZaxis()->SetLabelSize(0.05);
   Shower_E__11->GetZaxis()->SetTitleSize(0.05);
   Shower_E__11->GetZaxis()->SetTitleOffset(1);
   Shower_E__11->GetZaxis()->SetTitleFont(42);
   Shower_E__11->Draw("same");
   
   TH1D *Shower_E__12 = new TH1D("Shower_E__12","Shower_E",300,0,0.75);
   Shower_E__12->SetBinContent(14,2);
   Shower_E__12->SetBinContent(15,10);
   Shower_E__12->SetBinContent(16,42);
   Shower_E__12->SetBinContent(17,102);
   Shower_E__12->SetBinContent(18,141);
   Shower_E__12->SetBinContent(19,213);
   Shower_E__12->SetBinContent(20,195);
   Shower_E__12->SetBinContent(21,147);
   Shower_E__12->SetBinContent(22,75);
   Shower_E__12->SetBinContent(23,39);
   Shower_E__12->SetBinContent(24,20);
   Shower_E__12->SetBinContent(25,11);
   Shower_E__12->SetBinContent(26,2);
   Shower_E__12->SetEntries(999);
   Shower_E__12->SetStats(0);

   ci = TColor::GetColor("#33ff33");
   Shower_E__12->SetLineColor(ci);
   Shower_E__12->SetLineWidth(2);
   Shower_E__12->SetMarkerStyle(20);
   Shower_E__12->SetMarkerSize(1.2);
   Shower_E__12->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__12->GetXaxis()->SetLabelFont(42);
   Shower_E__12->GetXaxis()->SetLabelSize(0.05);
   Shower_E__12->GetXaxis()->SetTitleSize(0.05);
   Shower_E__12->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__12->GetXaxis()->SetTitleFont(42);
   Shower_E__12->GetYaxis()->SetTitle("N positron");
   Shower_E__12->GetYaxis()->SetLabelFont(42);
   Shower_E__12->GetYaxis()->SetLabelSize(0.05);
   Shower_E__12->GetYaxis()->SetTitleSize(0.05);
   Shower_E__12->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__12->GetYaxis()->SetTitleFont(42);
   Shower_E__12->GetZaxis()->SetLabelFont(42);
   Shower_E__12->GetZaxis()->SetLabelSize(0.05);
   Shower_E__12->GetZaxis()->SetTitleSize(0.05);
   Shower_E__12->GetZaxis()->SetTitleOffset(1);
   Shower_E__12->GetZaxis()->SetTitleFont(42);
   Shower_E__12->Draw("same");
   
   TH1D *Shower_E__13 = new TH1D("Shower_E__13","Shower_E",300,0,0.75);
   Shower_E__13->SetBinContent(6,2);
   Shower_E__13->SetBinContent(7,15);
   Shower_E__13->SetBinContent(8,95);
   Shower_E__13->SetBinContent(9,245);
   Shower_E__13->SetBinContent(10,299);
   Shower_E__13->SetBinContent(11,204);
   Shower_E__13->SetBinContent(12,109);
   Shower_E__13->SetBinContent(13,19);
   Shower_E__13->SetBinContent(14,11);
   Shower_E__13->SetEntries(999);
   Shower_E__13->SetStats(0);

   ci = TColor::GetColor("#006600");
   Shower_E__13->SetLineColor(ci);
   Shower_E__13->SetLineStyle(2);
   Shower_E__13->SetLineWidth(2);
   Shower_E__13->SetMarkerStyle(20);
   Shower_E__13->SetMarkerSize(1.2);
   Shower_E__13->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__13->GetXaxis()->SetLabelFont(42);
   Shower_E__13->GetXaxis()->SetLabelSize(0.05);
   Shower_E__13->GetXaxis()->SetTitleSize(0.05);
   Shower_E__13->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__13->GetXaxis()->SetTitleFont(42);
   Shower_E__13->GetYaxis()->SetTitle("N positron");
   Shower_E__13->GetYaxis()->SetLabelFont(42);
   Shower_E__13->GetYaxis()->SetLabelSize(0.05);
   Shower_E__13->GetYaxis()->SetTitleSize(0.05);
   Shower_E__13->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__13->GetYaxis()->SetTitleFont(42);
   Shower_E__13->GetZaxis()->SetLabelFont(42);
   Shower_E__13->GetZaxis()->SetLabelSize(0.05);
   Shower_E__13->GetZaxis()->SetTitleSize(0.05);
   Shower_E__13->GetZaxis()->SetTitleOffset(1);
   Shower_E__13->GetZaxis()->SetTitleFont(42);
   Shower_E__13->Draw("same");
   
   TH1D *Shower_E__14 = new TH1D("Shower_E__14","Shower_E",300,0,0.75);
   Shower_E__14->SetBinContent(6,2);
   Shower_E__14->SetBinContent(7,22);
   Shower_E__14->SetBinContent(8,123);
   Shower_E__14->SetBinContent(9,261);
   Shower_E__14->SetBinContent(10,297);
   Shower_E__14->SetBinContent(11,180);
   Shower_E__14->SetBinContent(12,88);
   Shower_E__14->SetBinContent(13,21);
   Shower_E__14->SetBinContent(14,5);
   Shower_E__14->SetEntries(999);
   Shower_E__14->SetStats(0);

   ci = TColor::GetColor("#006600");
   Shower_E__14->SetLineColor(ci);
   Shower_E__14->SetLineWidth(2);
   Shower_E__14->SetMarkerStyle(20);
   Shower_E__14->SetMarkerSize(1.2);
   Shower_E__14->GetXaxis()->SetTitle("Shower Energy deposition (GeV)");
   Shower_E__14->GetXaxis()->SetLabelFont(42);
   Shower_E__14->GetXaxis()->SetLabelSize(0.05);
   Shower_E__14->GetXaxis()->SetTitleSize(0.05);
   Shower_E__14->GetXaxis()->SetTitleOffset(1.4);
   Shower_E__14->GetXaxis()->SetTitleFont(42);
   Shower_E__14->GetYaxis()->SetTitle("N positron");
   Shower_E__14->GetYaxis()->SetLabelFont(42);
   Shower_E__14->GetYaxis()->SetLabelSize(0.05);
   Shower_E__14->GetYaxis()->SetTitleSize(0.05);
   Shower_E__14->GetYaxis()->SetTitleOffset(1.4);
   Shower_E__14->GetYaxis()->SetTitleFont(42);
   Shower_E__14->GetZaxis()->SetLabelFont(42);
   Shower_E__14->GetZaxis()->SetLabelSize(0.05);
   Shower_E__14->GetZaxis()->SetTitleSize(0.05);
   Shower_E__14->GetZaxis()->SetTitleOffset(1);
   Shower_E__14->GetZaxis()->SetTitleFont(42);
   Shower_E__14->Draw("same");
   
   TLegend *leg = new TLegend(0.52,0.5,0.92,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.04);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","e^{+} Energy","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextAlign(22);
   entry->SetTextFont(42);
   entry=leg->AddEntry("NULL","w/ beam bkg","");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("NULL","w/o beam bkg","");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","14 GeV","l");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","14 GeV","l");

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","12 GeV","l");

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","12 GeV","l");

   ci = TColor::GetColor("#ff00ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","10 GeV","l");

   ci = TColor::GetColor("#ff0033");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","10 GeV","l");

   ci = TColor::GetColor("#ff0033");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","8 GeV","l");

   ci = TColor::GetColor("#cc0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","8 GeV","l");

   ci = TColor::GetColor("#cc0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","6 GeV","l");

   ci = TColor::GetColor("#ff9900");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","6 GeV","l");

   ci = TColor::GetColor("#ff9900");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","4 GeV","l");

   ci = TColor::GetColor("#33ff33");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","4 GeV","l");

   ci = TColor::GetColor("#33ff33");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","2 GeV","l");

   ci = TColor::GetColor("#006600");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Shower_E","2 GeV","l");

   ci = TColor::GetColor("#006600");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.2,0.85,"LUXE");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2982959,0.85,"CDR");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.8,"Calorimeter - #gamma-laser");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1D *Shower_E_copy__15 = new TH1D("Shower_E_copy__15","Shower_E",300,0,0.75);
   Shower_E_copy__15->SetBinContent(46,1);
   Shower_E_copy__15->SetBinContent(59,1);
   Shower_E_copy__15->SetBinContent(62,1);
   Shower_E_copy__15->SetBinContent(63,1);
   Shower_E_copy__15->SetBinContent(64,2);
   Shower_E_copy__15->SetBinContent(65,4);
   Shower_E_copy__15->SetBinContent(66,1);
   Shower_E_copy__15->SetBinContent(67,13);
   Shower_E_copy__15->SetBinContent(68,19);
   Shower_E_copy__15->SetBinContent(69,21);
   Shower_E_copy__15->SetBinContent(70,28);
   Shower_E_copy__15->SetBinContent(71,44);
   Shower_E_copy__15->SetBinContent(72,51);
   Shower_E_copy__15->SetBinContent(73,55);
   Shower_E_copy__15->SetBinContent(74,87);
   Shower_E_copy__15->SetBinContent(75,96);
   Shower_E_copy__15->SetBinContent(76,73);
   Shower_E_copy__15->SetBinContent(77,100);
   Shower_E_copy__15->SetBinContent(78,94);
   Shower_E_copy__15->SetBinContent(79,74);
   Shower_E_copy__15->SetBinContent(80,67);
   Shower_E_copy__15->SetBinContent(81,49);
   Shower_E_copy__15->SetBinContent(82,34);
   Shower_E_copy__15->SetBinContent(83,29);
   Shower_E_copy__15->SetBinContent(84,21);
   Shower_E_copy__15->SetBinContent(85,10);
   Shower_E_copy__15->SetBinContent(86,10);
   Shower_E_copy__15->SetBinContent(87,3);
   Shower_E_copy__15->SetBinContent(88,2);
   Shower_E_copy__15->SetBinContent(89,2);
   Shower_E_copy__15->SetBinContent(90,4);
   Shower_E_copy__15->SetBinContent(91,1);
   Shower_E_copy__15->SetBinContent(94,1);
   Shower_E_copy__15->SetMinimum(0);
   Shower_E_copy__15->SetMaximum(400);
   Shower_E_copy__15->SetEntries(999);
   Shower_E_copy__15->SetDirectory(0);
   Shower_E_copy__15->SetStats(0);

   ci = TColor::GetColor("#0000ff");
   Shower_E_copy__15->SetLineColor(ci);
   Shower_E_copy__15->SetLineStyle(2);
   Shower_E_copy__15->SetLineWidth(2);
   Shower_E_copy__15->SetMarkerStyle(20);
   Shower_E_copy__15->SetMarkerSize(1.2);
   Shower_E_copy__15->GetXaxis()->SetTitle("Shower Energy Deposition (GeV)");
   Shower_E_copy__15->GetXaxis()->SetRange(1,100);
   Shower_E_copy__15->GetXaxis()->SetLabelFont(42);
   Shower_E_copy__15->GetXaxis()->SetLabelSize(0.05);
   Shower_E_copy__15->GetXaxis()->SetTitleSize(0.05);
   Shower_E_copy__15->GetXaxis()->SetTitleOffset(1.4);
   Shower_E_copy__15->GetXaxis()->SetTitleFont(42);
   Shower_E_copy__15->GetYaxis()->SetTitle("Arbirtary Units");
   Shower_E_copy__15->GetYaxis()->SetLabelFont(42);
   Shower_E_copy__15->GetYaxis()->SetLabelSize(0.05);
   Shower_E_copy__15->GetYaxis()->SetTitleSize(0.05);
   Shower_E_copy__15->GetYaxis()->SetTitleOffset(1.4);
   Shower_E_copy__15->GetYaxis()->SetTitleFont(42);
   Shower_E_copy__15->GetZaxis()->SetLabelFont(42);
   Shower_E_copy__15->GetZaxis()->SetLabelSize(0.05);
   Shower_E_copy__15->GetZaxis()->SetTitleSize(0.05);
   Shower_E_copy__15->GetZaxis()->SetTitleOffset(1);
   Shower_E_copy__15->GetZaxis()->SetTitleFont(42);
   Shower_E_copy__15->Draw("sameaxis");
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
